In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
 # DataFrame oluşturma (kodlar)

stn_boy = np.random.randint(150,190,(10))
stn_kilo = np.random.randint(50,100,(10))
stn_no = np.random.randint(2100,2200,(10))

# pandas kütüphanesi , dictionary veri yapısı üzerine kurulmuştur 
# pandas kütüphanesi ile excel ve sql deki her şeyi yapabiliriz

my_dict = {"ogr_no":stn_no,"ogr_boy":stn_boy,"ogr_kilo":stn_kilo}

my_df = pd.DataFrame.from_dict(my_dict)
my_df

ogr_no  ogr_boy  ogr_kilo
0    2106      160        67
1    2152      174        66
2    2181      163        81
3    2118      167        69
4    2134      177        63
5    2103      186        64
6    2102      160        82
7    2187      153        58
8    2134      182        92
9    2131      160        54

In [4]:
my_df.index

RangeIndex(start=0, stop=10, step=1)

In [6]:
my_df.index = ["ogrenci_1","ogrenci_2","ogrenci_3","ogrenci_4","ogrenci_5","ogrenci_6","ogrenci_7","ogrenci_8","ogrenci_9","ogrenci_10"]
my_df

ogr_no  ogr_boy  ogr_kilo
ogrenci_1     2106      160        67
ogrenci_2     2152      174        66
ogrenci_3     2181      163        81
ogrenci_4     2118      167        69
ogrenci_5     2134      177        63
ogrenci_6     2103      186        64
ogrenci_7     2102      160        82
ogrenci_8     2187      153        58
ogrenci_9     2134      182        92
ogrenci_10    2131      160        54

In [7]:
# dataframe ye yeni sütun ve değerler ekleme

stn_vize = np.random.randint(20,100,(10))
stn_final = np.random.randint(20,100,(10))

my_df["ogr_vize"] = stn_vize
my_df["ogr_final"] = stn_final
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final
ogrenci_1     2106      160        67        62         45
ogrenci_2     2152      174        66        77         29
ogrenci_3     2181      163        81        59         68
ogrenci_4     2118      167        69        34         75
ogrenci_5     2134      177        63        52         85
ogrenci_6     2103      186        64        79         41
ogrenci_7     2102      160        82        43         54
ogrenci_8     2187      153        58        56         60
ogrenci_9     2134      182        92        43         58
ogrenci_10    2131      160        54        53         80

In [8]:
deger_vize = my_df["ogr_vize"].values
deger_final = my_df["ogr_final"].values

In [9]:
deger_vize

array([62, 77, 59, 34, 52, 79, 43, 56, 43, 53])

In [10]:
deger_final

array([45, 29, 68, 75, 85, 41, 54, 60, 58, 80])

In [11]:
deger_vize*2

array([124, 154, 118,  68, 104, 158,  86, 112,  86, 106])

In [17]:
# ogr_gecti isimli bir key ekleyn
# bu keyin değerleri vize notlarının yüzde kırkı ile
#final notlarının yüzde altmışının toplamı olucak

son_not= (my_df["ogr_vize"].values*0.4) + (my_df["ogr_final"].values*0.6)
my_df ["ogr_gecti"] = son_not




my_df





ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti
ogrenci_1     2106      160        67        62         45       51.8
ogrenci_2     2152      174        66        77         29       48.2
ogrenci_3     2181      163        81        59         68       64.4
ogrenci_4     2118      167        69        34         75       58.6
ogrenci_5     2134      177        63        52         85       71.8
ogrenci_6     2103      186        64        79         41       56.2
ogrenci_7     2102      160        82        43         54       49.6
ogrenci_8     2187      153        58        56         60       58.4
ogrenci_9     2134      182        92        43         58       52.0
ogrenci_10    2131      160        54        53         80       69.2

In [20]:
my_df["durum"] = my_df["ogr_gecti"].values>50
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum
ogrenci_1     2106      160        67        62         45       51.8   True
ogrenci_2     2152      174        66        77         29       48.2  False
ogrenci_3     2181      163        81        59         68       64.4   True
ogrenci_4     2118      167        69        34         75       58.6   True
ogrenci_5     2134      177        63        52         85       71.8   True
ogrenci_6     2103      186        64        79         41       56.2   True
ogrenci_7     2102      160        82        43         54       49.6  False
ogrenci_8     2187      153        58        56         60       58.4   True
ogrenci_9     2134      182        92        43         58       52.0   True
ogrenci_10    2131      160        54        53         80       69.2   True

In [21]:
my_df["cinsiyet"]="erkek"  #şart koyulmadığı için tüm sütunun adını erkek yaptı
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum  \
ogrenci_1     2106      160        67        62         45       51.8   True   
ogrenci_2     2152      174        66        77         29       48.2  False   
ogrenci_3     2181      163        81        59         68       64.4   True   
ogrenci_4     2118      167        69        34         75       58.6   True   
ogrenci_5     2134      177        63        52         85       71.8   True   
ogrenci_6     2103      186        64        79         41       56.2   True   
ogrenci_7     2102      160        82        43         54       49.6  False   
ogrenci_8     2187      153        58        56         60       58.4   True   
ogrenci_9     2134      182        92        43         58       52.0   True   
ogrenci_10    2131      160        54        53         80       69.2   True   

           cinsiyet  
ogrenci_1     erkek  
ogrenci_2     erkek  
ogrenci_3     erkek  
ogrenci_4     erkek  
ogrenci_5     erkek  
ogrenci_6     erkek  
ogrenci_7     erkek  
ogrenci_8     erkek  
ogrenci_9     erkek  
ogrenci_10    erkek

In [22]:
#istenilen özelliklere göre değer getirtme
# tek sorguya göre
my_df[my_df["ogr_vize"]<50]

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum  \
ogrenci_4    2118      167        69        34         75       58.6   True   
ogrenci_7    2102      160        82        43         54       49.6  False   
ogrenci_9    2134      182        92        43         58       52.0   True   

          cinsiyet  
ogrenci_4    erkek  
ogrenci_7    erkek  
ogrenci_9    erkek

In [25]:
#birden fazla sorguya göre değer çağırma
my_df[(my_df["ogr_vize"]<50) & (my_df["durum"]==True)]

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum  \
ogrenci_4    2118      167        69        34         75       58.6   True   
ogrenci_9    2134      182        92        43         58       52.0   True   

          cinsiyet  
ogrenci_4    erkek  
ogrenci_9    erkek

In [27]:
my_ds = sns.load_dataset("titanic")
my_ds


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [29]:
#yabancı bir veri seti gördüğünüzde onu tanımak için 2 hazır fonksiyon 
# kullanın => .info() ve .describe()

my_ds.describe()  # istatistiki bilgiler için

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [30]:
my_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [31]:
my_ds.pivot_table("survived",index="sex",columns="class")

C:\Users\Monster\AppData\Local\Temp\ipykernel_3100\2593529420.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  my_ds.pivot_table("survived",index="sex",columns="class")


class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [39]:
sorgu=my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)

C:\Users\Monster\AppData\Local\Temp\ipykernel_3100\2065878591.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  sorgu=my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)
C:\Users\Monster\AppData\Local\Temp\ipykernel_3100\2065878591.py:1: FutureWarning: The provided callable <function sum at 0x0000020CD2A48AF0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sorgu=my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)


In [34]:
#VERİLERİ KAYDETME (EXCEL OLARAK)

pd.DataFrame.to_excel(my_df,"my_df.xlsx")


In [41]:
pd.DataFrame.to_excel(sorgu,"my_ds_pivot_table.xlsx")